import { useState, useEffect, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import { useToast } from '../context/ToastContext'
import { getTrip, deleteTrip, regenerateDay } from '../api/client'
import { OverviewMap, DayMap } from '../components/MapView'
import ScheduleCard from '../components/ScheduleCard'
import MemoriesPanel from '../components/MemoriesPanel'
import EditSpotModal from '../components/EditSpotModal'
import styles from './TripDetails.module.css'

const WEATHER_ICONS = {
  Clear:'☀️', Clouds:'☁️', Rain:'🌧️', Drizzle:'🌦️',
  Thunderstorm:'⛈️', Snow:'❄️', Mist:'🌫️', Fog:'🌫️',
}
function weatherIcon(c = '') {
  for (const [k, v] of Object.entries(WEATHER_ICONS))
    if (c.toLowerCase().includes(k.toLowerCase())) return v
  return '🌡️'
}

const STATUS_COLORS = {
  Upcoming:'#92C4C6', Ongoing:'#F3C375', Completed:'#20878E',
}
const SLOT_ORDER = ['Breakfast ☕','Morning 🌅','Lunch 🍔','Afternoon ☀️','Dinner 🍷','Evening 🌙']

// ── PDF export ────────────────────────────────────────────────────────────────
async function exportPDF(trip, spots, totalDays) {
  const html2pdf = (await import('html2pdf.js')).default
  const fmt = d => d ? new Date(d+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}) : ''
  const hotelSpots = spots.filter(s => s.category === 'Hotel')
  const nightly    = hotelSpots.length ? Math.max(...hotelSpots.map(s => s.cost)) : 0
  const actSum     = [...new Map(spots.filter(s=>s.category!=='Hotel').map(s=>[s.day_num+'-'+s.name,s])).values()].reduce((a,r)=>a+r.cost,0)
  const misc       = 40 * trip.days
  const dayBlocks  = Array.from({length:totalDays},(_,i)=>i+1).map(d => {
    const ds   = spots.filter(s=>s.day_num===d).sort((a,b)=>SLOT_ORDER.indexOf(a.slot)-SLOT_ORDER.indexOf(b.slot))
    const rows = ds.map(s=>'<tr><td style="padding:6px 10px;font-size:12px;color:#555;">'+s.slot+'</td><td style="padding:6px 10px;font-size:12px;font-weight:600;">'+s.name+'</td><td style="padding:6px 10px;font-size:12px;color:#555;">'+s.category+'</td><td style="padding:6px 10px;font-size:12px;text-align:right;color:#20878E;font-weight:700;">'+( s.cost===0?'Free':'$'+s.cost)+'</td></tr>').join('')
    return '<div style="margin-bottom:20px;"><div style="background:#20878E;color:white;padding:7px 12px;font-weight:800;font-size:13px;">Day '+d+'</div><table style="width:100%;border-collapse:collapse;"><thead><tr style="background:#f5f5f5;"><th style="padding:5px 10px;text-align:left;font-size:11px;color:#888;">Time</th><th style="padding:5px 10px;text-align:left;font-size:11px;color:#888;">Place</th><th style="padding:5px 10px;text-align:left;font-size:11px;color:#888;">Category</th><th style="padding:5px 10px;text-align:right;font-size:11px;color:#888;">Cost</th></tr></thead><tbody>'+rows+'</tbody></table></div>'
  }).join('')
  const content = document.createElement('div')
  content.style.fontFamily = 'Arial, sans-serif'
  content.innerHTML = '<div style="background:linear-gradient(135deg,#20878E,#0d5a60);color:white;border-radius:10px;padding:24px 28px;margin-bottom:20px;"><div style="font-size:11px;opacity:0.7;margin-bottom:4px;">Wandr — Itinerary Export</div><h1 style="font-size:24px;font-weight:800;margin-bottom:3px;">'+trip.city+'</h1><div style="font-size:13px;opacity:0.8;font-style:italic;margin-bottom:10px;">'+trip.title+'</div><div style="font-size:12px;">'+trip.days+' day'+(trip.days>1?'s':'')+(trip.start_date?' · '+fmt(trip.start_date)+' → '+fmt(trip.end_date):'')+' · '+trip.status+'</div></div><h2 style="font-size:15px;font-weight:800;color:#1a1a1a;margin-bottom:14px;">Full Schedule</h2>'+dayBlocks+'<div style="text-align:center;color:#aaa;font-size:11px;margin-top:24px;padding-top:12px;border-top:1px solid #eee;">Generated by Wandr</div>'
  const filename = trip.title.replace(/[^a-z0-9]/gi,'_')+'_Wandr.pdf'
  await html2pdf().set({
    margin:[10,10,10,10], filename,
    image:{type:'jpeg',quality:0.95},
    html2canvas:{scale:2,useCORS:true},
    jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},
  }).from(content).save()
}

// ── Main ──────────────────────────────────────────────────────────────────────
export default function TripDetails() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { removeTrip, trips, locations } = useApp()
  const toast = useToast()

  const cached = trips.find(t => t.id === id)
  const [trip, setTrip]           = useState(cached ?? null)
  const [loading, setLoading]     = useState(!cached)
  const [tab, setTab]             = useState('overview')   // 'overview' | 'day'
  const [selectedDay, setDay]     = useState(1)
  const [confirmDel, setConfirm]  = useState(false)
  const [deleting, setDeleting]   = useState(false)
  const [routeKm, setRouteKm]     = useState(null)
  const [editingSpot, setEditingSpot] = useState(null)
  const [regenLoading, setRegenLoad]  = useState(false)
  const [shareToast, setShareToast]   = useState(false)
  const [sidebarOpen, setSidebar]     = useState(false)
  const [expandedDays, setExpanded]   = useState({ 1: true })

  useEffect(() => {
    if (cached) return
    getTrip(id).then(setTrip).catch(() => setTrip(null)).finally(() => setLoading(false))
  }, [id])

  useEffect(() => { setRouteKm(null) }, [selectedDay])

  const handleSpotSwapped = useCallback((updated) => {
    setTrip(prev => !prev ? prev : {
      ...prev,
      spots: prev.spots.map(s => s.id === updated.id ? { ...s, ...updated } : s)
    })
  }, [])

  async function handleRegenerate() {
    setRegenLoad(true)
    try {
      const result = await regenerateDay(id, selectedDay)
      setTrip(prev => {
        if (!prev) return prev
        const kept = prev.spots.filter(s => s.day_num !== selectedDay)
        const merged = [...kept, ...result.new_spots]
          .sort((a,b) => a.day_num - b.day_num || SLOT_ORDER.indexOf(a.slot) - SLOT_ORDER.indexOf(b.slot))
        return { ...prev, spots: merged, cost: result.new_cost }
      })
      toast.success(`Day ${selectedDay} regenerated!`)
    } catch (e) {
      toast.error(e.message || 'Could not regenerate day.')
    } finally {
      setRegenLoad(false)
    }
  }

  function handleShare() {
    const url = `${window.location.origin}/share/${id}`
    navigator.clipboard.writeText(url)
      .then(() => { setShareToast(true); setTimeout(() => setShareToast(false), 2500) })
      .catch(() => prompt('Copy this link:', url))
  }

  async function handleDelete() {
    setDeleting(true)
    try { await deleteTrip(id); removeTrip(id); toast.success('Trip deleted.'); navigate('/') }
    catch { toast.error('Could not delete.'); setDeleting(false); setConfirm(false) }
  }

  function goBack() {
    navigate('/', { state: { view: 'trips' } })
  }

  if (loading) return (
    <div style={{ display:'flex', alignItems:'center', justifyContent:'center', height:'100vh' }}>
      <div className="spinner" style={{ width:32, height:32 }} />
    </div>
  )
  if (!trip) return (
    <div style={{ textAlign:'center', padding:'4rem' }}>
      <p style={{ color:'var(--muted)', marginBottom:'1rem' }}>Trip not found.</p>
      <button className="btn btn-primary" onClick={goBack}>Back to My Trips</button>
    </div>
  )

  const { spots=[], forecast={}, weather, days, title, city, cost, status } = trip
  const cond     = weather?.condition ?? 'Unknown'
  const temp     = weather?.temp ?? '--'
  const sc       = STATUS_COLORS[status] ?? STATUS_COLORS.Upcoming
  const totalDays = spots.length ? Math.max(...spots.map(s => s.day_num ?? 1)) : 1

  // Budget
  const hotelSpots = spots.filter(s => s.category === 'Hotel')
  const nightly    = hotelSpots.length ? Math.max(...hotelSpots.map(s => s.cost)) : 0
  const actSum     = [...new Map(
    spots.filter(s=>s.category!=='Hotel').map(s=>[`${s.day_num}-${s.name}`,s])
  ).values()].reduce((a,r)=>a+r.cost,0)
  const miscTotal  = 40 * days

  // Day data
  const daySpots = spots
    .filter(s => s.day_num === selectedDay)
    .sort((a,b) => SLOT_ORDER.indexOf(a.slot) - SLOT_ORDER.indexOf(b.slot))

  const dayNightly = (() => {
    const dh = daySpots.filter(s=>s.category==='Hotel')
    return dh.length ? Math.max(...dh.map(s=>s.cost)) : 0
  })()
  const dayActSum = [...new Map(
    daySpots.filter(s=>s.category!=='Hotel').map(s=>[s.name,s])
  ).values()].reduce((a,r)=>a+r.cost,0)

  const forecastDates = Object.keys(forecast).sort()
  const [fc_cond, fc_temp] = forecastDates[selectedDay-1]
    ? (forecast[forecastDates[selectedDay-1]] ?? [cond,temp])
    : [cond,temp]

  const hotelName = hotelSpots[0]?.name ?? null
  const isSwappable = s => !s.name?.includes('(Rest & Settle)')

  function formatDate(d) {
    if (!d) return ''
    return new Date(d+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})
  }

  // ── Sidebar content (shared between desktop sidebar + mobile sheet) ──────────
  const SidebarContent = () => (
    <>
      {/* Trip identity */}
      <div className={styles.sideTrip}>
        <div className={styles.sideCity}>{city}</div>
        <div className={styles.sideTitle}>"{title}"</div>
        <div className={styles.sideMeta}>
          <span className={styles.sideStatus}
            style={{ background:`${sc}22`, color:sc, borderColor:sc }}>
            {status}
          </span>
          <span className={styles.sideDays}>{days} day{days>1?'s':''}</span>
        </div>
        {trip.start_date && (
          <div className={styles.sideDates}>
            {formatDate(trip.start_date)} → {formatDate(trip.end_date)}
          </div>
        )}
        {hotelName && <div className={styles.sideHotel}>{hotelName}</div>}
      </div>

      {/* Budget */}
      <div className={styles.sideBudget}>
        <div className={styles.sideLabel}>Budget Overview</div>
        <div className={styles.sideBudgetTotal}>
          ${Number(cost).toLocaleString(undefined,{maximumFractionDigits:0})}
          <span className={styles.sideBudgetSub}> estimated</span>
        </div>
        {[
          [`Hotel (${days} nights)`, nightly*days],
          ['Activities', actSum],
          [`Misc (${days} days)`, miscTotal],
        ].map(([l,a]) => (
          <div key={l} className={styles.sideBudgetRow}>
            <span>{l}</span>
            <span>${Number(a).toLocaleString(undefined,{maximumFractionDigits:0})}</span>
          </div>
        ))}
      </div>

      {/* Day nav */}
      <div className={styles.sideDayNav}>
        <div className={styles.sideLabel}>Days</div>
        {Array.from({length:totalDays},(_,i)=>i+1).map(d => {
          const count = spots.filter(s=>s.day_num===d).length
          return (
            <button key={d}
              className={`${styles.dayNavItem} ${selectedDay===d && tab==='day' ? styles.dayNavActive : ''}`}
              onClick={() => { setDay(d); setTab('day'); setSidebar(false) }}>
              <span className={styles.dayNavNum}>Day {d}</span>
              <span className={styles.dayNavCount}>{count} stops</span>
            </button>
          )
        })}
      </div>

      {/* Actions */}
      <div className={styles.sideActions}>
        <button className={styles.actionBtn} onClick={handleShare}>
          Share Trip
        </button>
        <button className={styles.actionBtn} onClick={() => exportPDF(trip, spots, totalDays)}>
          Export PDF
        </button>
        {confirmDel ? (
          <div className={styles.deleteConfirm}>
            <p>This will permanently delete the trip.</p>
            <div style={{display:'flex',gap:'6px',marginTop:'6px'}}>
              <button className={`${styles.actionBtn} ${styles.actionBtnDanger} ${styles.actionBtnFlex}`}
                onClick={handleDelete} disabled={deleting}>
                {deleting ? 'Deleting…' : 'Confirm Delete'}
              </button>
              <button className={`${styles.actionBtn} ${styles.actionBtnFlex}`}
                onClick={() => setConfirm(false)}>
                Cancel
              </button>
            </div>
          </div>
        ) : (
          <button className={`${styles.actionBtn} ${styles.actionBtnDanger}`}
            onClick={() => setConfirm(true)}>
            Delete Trip
          </button>
        )}
      </div>
    </>
  )

  return (
    <div className={styles.shell}>

      {/* ══ LEFT SIDEBAR (desktop) ══ */}
      <aside className={styles.sidebar}>
        <button className={styles.backBtn} onClick={goBack}>← Back</button>
        <SidebarContent />
      </aside>

      {/* ══ MAIN CONTENT ══ */}
      <main className={styles.main}>

        {/* Top bar */}
        <div className={styles.topBar}>
          {/* Mobile: back + sidebar toggle */}
          <button className={styles.mobileBack} onClick={goBack}>← Back</button>

          {/* Tab switcher */}
          <div className={styles.tabSwitcher}>
            <button
              className={`${styles.tabBtn} ${tab==='overview' ? styles.tabBtnActive : ''}`}
              onClick={() => setTab('overview')}>
              Overview
            </button>
            <button
              className={`${styles.tabBtn} ${tab==='day' ? styles.tabBtnActive : ''}`}
              onClick={() => setTab('day')}>
              Day {selectedDay}
            </button>
          </div>

          {/* Day controls (only in day tab) */}
          {tab === 'day' && (
            <div className={styles.dayControls}>
              <div className={styles.dayChips}>
                {Array.from({length:totalDays},(_,i)=>i+1).map(d => (
                  <button key={d}
                    className={`${styles.dayChip} ${selectedDay===d ? styles.dayChipActive : ''}`}
                    onClick={() => setDay(d)}>
                    {d}
                  </button>
                ))}
              </div>
              <button
                className={styles.regenBtn}
                onClick={handleRegenerate}
                disabled={regenLoading}>
                {regenLoading
                  ? <span className="spinner" style={{width:12,height:12}}/>
                  : null}
                Re-roll Day
              </button>
            </div>
          )}

          {/* Mobile sidebar toggle */}
          <button className={styles.sidebarToggle} onClick={() => setSidebar(true)}>
            Details
          </button>
        </div>

        {/* ══ OVERVIEW TAB ══ */}
        {tab === 'overview' && (
          <div className={styles.overviewContent}>
            {/* Hero card */}
            <div className={styles.overviewHero}>
              <div className={styles.overviewHeroTop}>
                <div className={styles.overviewHeroLeft}>
                  <h1 className={styles.overviewCity}>{city}</h1>
                  <div className={styles.overviewTripTitle}>"{title}"</div>
                  <div className={styles.overviewMeta}>
                    <span className={styles.statusPill}
                      style={{ background:`${sc}22`, color:sc, borderColor:sc }}>
                      {status}
                    </span>
                    {trip.start_date && (
                      <span className={styles.metaChip}>
                        {formatDate(trip.start_date)} → {formatDate(trip.end_date)}
                      </span>
                    )}
                  </div>
                </div>
                {hotelName && (
                  <div className={styles.overviewHotelBadge}>
                    <span className={styles.overviewHotelLabel}>Staying at</span>
                    <span className={styles.overviewHotelName}>{hotelName}</span>
                  </div>
                )}
              </div>

              {/* Stats strip */}
              <div className={styles.heroStats}>
                <div className={styles.heroStat}>
                  <div className={styles.heroStatNum}>{days}</div>
                  <div className={styles.heroStatLabel}>Days</div>
                </div>
                <div className={styles.heroStat}>
                  <div className={styles.heroStatNum}>{totalDays}</div>
                  <div className={styles.heroStatLabel}>Planned</div>
                </div>
                <div className={styles.heroStat}>
                  <div className={styles.heroStatNum}>{spots.filter(s=>s.category!=='Hotel').length}</div>
                  <div className={styles.heroStatLabel}>Stops</div>
                </div>
                <div className={styles.heroStat}>
                  <div className={styles.heroStatNum}>${Number(cost).toLocaleString(undefined,{maximumFractionDigits:0,notation:'compact'})}</div>
                  <div className={styles.heroStatLabel}>Budget</div>
                </div>
              </div>
            </div>

            {/* Budget row */}
            <div className={styles.budgetRow}>
              {[
                { label:'Total Estimated', amount: cost, g:'linear-gradient(135deg,#1a1a1a,#333)', sub:`${days} days` },
                { label:`Hotel`, amount: nightly*days, g:'linear-gradient(135deg,#20878E,#92C4C6)', sub:`$${nightly}/night` },
                { label:'Activities', amount: actSum, g:'linear-gradient(135deg,#92C4C6,#F3C375)', sub:'All stops' },
                { label:'Misc & Transport', amount: miscTotal, g:'linear-gradient(135deg,#F3C375,#D66F29)', sub:'$40/day' },
              ].map(({label,amount,g,sub}) => (
                <div key={label} className={styles.budgetBox} style={{background:g}}>
                  <div className={styles.budgetLabel}>{label}</div>
                  <div className={styles.budgetAmount}>${Number(amount).toLocaleString(undefined,{maximumFractionDigits:0})}</div>
                  <div className={styles.budgetSub}>{sub}</div>
                </div>
              ))}
            </div>

            {/* Full trip map */}
            <div className={styles.overviewMapWrap}>
              <div className={styles.sectionHeader}>
                <h3 className={styles.sectionTitle}>All Stops</h3>
                <div className={styles.mapLegend}>
                  <span><span className={styles.dot} style={{background:'#D66F29'}}>H</span> Hotel</span>
                  <span><span className={styles.dot} style={{background:'#c8860a'}}>1</span> Food</span>
                  <span><span className={styles.dot} style={{background:'#20878E'}}>1</span> Sightseeing</span>
                </div>
              </div>
              {spots.length > 0
                ? <OverviewMap spots={spots} />
                : <div className={styles.empty}>No spots yet.</div>}
            </div>

            {/* Full schedule — collapsible per day */}
            <div className={styles.overviewSchedule}>
              <h3 className={styles.sectionTitle}>Full Schedule</h3>
              {Array.from({length:totalDays},(_,i)=>i+1).map(d => {
                const ds = spots.filter(s=>s.day_num===d)
                  .sort((a,b)=>SLOT_ORDER.indexOf(a.slot)-SLOT_ORDER.indexOf(b.slot))
                return (
                  <div key={d} className={styles.dayBlock}>
                    <button
                      className={styles.dayToggle}
                      onClick={() => setExpanded(p=>({...p,[d]:!p[d]}))}>
                      <span className={styles.dayToggleLabel}>Day {d}</span>
                      <span className={styles.dayToggleMeta}>{ds.length} stops</span>
                      <span className={styles.dayToggleArrow}>{expandedDays[d]?'▲':'▼'}</span>
                    </button>
                    {expandedDays[d] && ds.map((s,i) => (
                      <div key={i} className={styles.spotRow}>
                        <div className={styles.spotCard}><ScheduleCard spot={s} /></div>
                        {isSwappable(s) ? (
                          <button className={styles.swapBtn} onClick={() => setEditingSpot(s)}>
                            Swap
                          </button>
                        ) : <div className={styles.swapPlaceholder}/>}
                      </div>
                    ))}
                  </div>
                )
              })}
            </div>
          </div>
        )}

        {/* ══ DAY TAB ══ */}
        {tab === 'day' && (
          <div className={styles.dayContent}>
            {/* Day map */}
            <div className={styles.dayMapWrap}>
              <DayMap
                spots={daySpots}
                dayKey={`day-${selectedDay}`}
                onDistanceCalculated={setRouteKm}
              />
              <div className={styles.mapLegend}>
                <span><span className={styles.dot} style={{background:'#D66F29'}}>H</span> Hotel</span>
                <span><span className={styles.dot} style={{background:'#c8860a'}}>1</span> Food</span>
                <span><span className={styles.dot} style={{background:'#20878E'}}>1</span> Sightseeing</span>
              </div>
            </div>

            {/* Day schedule */}
            <div className={styles.daySchedule}>
              <h3 className={styles.sectionTitle}>Day {selectedDay} Schedule</h3>
              {daySpots.length === 0
                ? <div className={styles.empty}>No spots for this day.</div>
                : daySpots.map((s,i) => (
                  <div key={i} className={styles.spotRow}>
                    <div className={styles.spotCard}><ScheduleCard spot={s} /></div>
                    {isSwappable(s) ? (
                      <button className={styles.swapBtn} onClick={() => setEditingSpot(s)}>Swap</button>
                    ) : <div className={styles.swapPlaceholder}/>}
                  </div>
                ))}
            </div>

            {/* Memories */}
            <MemoriesPanel tripId={id} dayNum={selectedDay} />
          </div>
        )}
      </main>

      {/* ══ RIGHT PANEL (desktop only — weather + day budget) ══ */}
      <aside className={styles.rightPanel}>
        <div className={styles.rpCard}>
          <div className={styles.rpLabel}>
            {tab === 'day' ? `Day ${selectedDay} Weather` : 'Current Weather'}
          </div>
          <div className={styles.weatherRow}>
            <span className={styles.weatherEmoji}>{weatherIcon(fc_cond)}</span>
            <div>
              <div className={styles.weatherCond}>{fc_cond}</div>
              <div className={styles.weatherTemp}>{fc_temp}°C</div>
            </div>
          </div>
          {routeKm !== null && routeKm > 0 && (
            <div className={styles.distRow}>Drive distance: <strong>{routeKm.toFixed(1)} km</strong></div>
          )}
        </div>

        {tab === 'day' && (
          <div className={styles.rpCard}>
            <div className={styles.rpLabel}>Day {selectedDay} Budget</div>
            <div className={styles.dayBudgetGrid}>
              {[
                ['Hotel', dayNightly, 'linear-gradient(135deg,#20878E,#92C4C6)'],
                ['Activities', dayActSum, 'linear-gradient(135deg,#92C4C6,#F3C375)'],
                ['Misc', 40, 'linear-gradient(135deg,#F3C375,#D66F29)'],
                ['Total', dayNightly+dayActSum+40, 'linear-gradient(135deg,#1a1a1a,#333)'],
              ].map(([l,a,g]) => (
                <div key={l} className={styles.dbBox} style={{background:g}}>
                  <div className={styles.dbLabel}>{l}</div>
                  <div className={styles.dbAmount}>${Number(a).toLocaleString(undefined,{maximumFractionDigits:0})}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {tab === 'overview' && (
          <div className={styles.rpCard}>
            <div className={styles.rpLabel}>Trip at a Glance</div>
            <div className={styles.glanceList}>
              <div className={styles.glanceRow}><span>Total days</span><strong>{days}</strong></div>
              <div className={styles.glanceRow}><span>Total stops</span><strong>{spots.length}</strong></div>
              <div className={styles.glanceRow}><span>Hotels</span><strong>{hotelSpots.length > 0 ? hotelSpots[0].name.split(' ').slice(0,2).join(' ') : '—'}</strong></div>
              <div className={styles.glanceRow}><span>Est. total</span><strong>${Number(cost).toLocaleString(undefined,{maximumFractionDigits:0})}</strong></div>
            </div>
          </div>
        )}
      </aside>

      {/* ══ MOBILE BOTTOM BAR ══ */}
      <div className={styles.mobileBar}>
        <button className={`${styles.mobileBarBtn} ${tab==='overview'?styles.mobileBarBtnActive:''}`}
          onClick={() => setTab('overview')}>
          Overview
        </button>
        <button className={`${styles.mobileBarBtn} ${tab==='day'?styles.mobileBarBtnActive:''}`}
          onClick={() => setTab('day')}>
          Day {selectedDay}
        </button>
        <button className={styles.mobileBarBtn} onClick={() => setSidebar(true)}>
          Details
        </button>
      </div>

      {/* ══ MOBILE SIDEBAR SHEET ══ */}
      {sidebarOpen && (
        <div className={styles.sheetOverlay} onClick={() => setSidebar(false)}>
          <div className={styles.sheet} onClick={e => e.stopPropagation()}>
            <div className={styles.sheetHandle} />
            <div className={styles.sheetScroll}>
              <SidebarContent />
            </div>
          </div>
        </div>
      )}

      {/* ── Modals & toasts ── */}
      {editingSpot && (
        <EditSpotModal
          spot={editingSpot}
          tripId={id}
          locations={locations}
          onClose={() => setEditingSpot(null)}
          onSwapped={handleSpotSwapped}
        />
      )}

      {shareToast && (
        <div className={styles.shareToast}>Link copied to clipboard</div>
      )}
    </div>
  )
}
